### ISSUE TITLE
Invalid view at live/production server

### ISSUE THREAD

**Issue by invasoria** [LCD344/Kirby-userManager-panel-extention#1]
Hello, I've uploaded a project to a test server and I get the following message once I try to open the userManager:

`Invalid view :/home/cpaneluser/subdomain.domain.com/site/plugins/UserManager/Panel/Views/UserManager/index.php`

It's working flawlessly in a local environment, I don't know what could be wrong.  :-/

**Comment by LCD344** [comment]
This is strange, could you post a photo of your folder structure? From what I know, the Invalid View error in kirby means that it can't find the file.

I have the userManager working on two different websites using cpanel.... (and of course local environment)

**Comment by invasoria** [comment]
Hi,
I just fixed this error by correcting the path at **plugins/userManager/Panel/Stubs/View.php**
After looking closely at the url in the error message I noticed that the plugin folder had a capital "U".

I changed this line:

`$this->_root = kirby()->roots()->plugins() . DS . "UserManager" . DS . "Panel" . DS . "Views";`

to:

`$this->_root = kirby()->roots()->plugins() . DS . "userManager" . DS . "Panel" . DS . "Views";`

I guess some environments are just a bit more strict with the case sensitive properties. :)

**Comment by LCD344** [comment]
Great catch! fixed.
