### ISSUE TITLE
editing the user form

### ISSUE THREAD

**Issue by EdwardLecock** [LCD344/Kirby-userManager-panel-extention#2]
Is there a way to overwrite the default user form you create in `Panel/Forms/user.php` via the options?
I would like to remove some of the fields and add some new ones. The only solution I see at the moment is editing the `Panel/Forms/user.php` file, which I'd rather not.

Edit: I've found that I can add fields via a blueprint, but still haven't found how to remove some of the default fields (e.g.: First name or last name)

**Comment by LCD344** [comment]
This is based on the kirby users system so I didn't include it as a feature. But I might add this to next iteration. or a pull request could also be a good!

I'm thinking something like a config flag to load blueprints from somewhere else maybe?

**Comment by EdwardLecock** [comment]
Yea, a config flag sounds good, or even just an array in the config like you did for the fields that should be shown in the datatable. I might come at you with a pull request later this week

**Comment by LCD344** [comment]
Actually I already resolved it in a commit right now. I added a userManager.overrideDefaultFields flag 

so `c::set('userManager.overrideDefaultFields',true);` will enable you to override them

then you need to write a yaml file named site\blueprints\users\userManager.override.yml (or whatever is your blueprint folder) with the new fields definitions - for example

```yaml
fields:
  role:
    label: role
    type: select
    options:
      user: user
      manager: manager
```

and viola! you'll have an override

Edit:

Note - Kirby requires username, password, passwordconfirmation and role fields to function - so I force you to have them. You can though, use the blueprint to override them (for example turn them hidden)
